// <auto-generated />
using Labb2Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb2Linq.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb2Linq.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Programmering 1",
                            TeacherId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Programmering 2",
                            TeacherId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Engelska",
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Matematik",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("Labb2Linq.Models.SchoolClass", b =>
                {
                    b.Property<int>("SchoolClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SchoolClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolClassId");

                    b.ToTable("SchoolClasses");

                    b.HasData(
                        new
                        {
                            SchoolClassId = 1,
                            SchoolClassName = "1a"
                        },
                        new
                        {
                            SchoolClassId = 2,
                            SchoolClassName = "1b"
                        });
                });

            modelBuilder.Entity("Labb2Linq.Models.SchoolClassCourse", b =>
                {
                    b.Property<int>("SchoolClassCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.HasKey("SchoolClassCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("SchoolClassCourses");

                    b.HasData(
                        new
                        {
                            SchoolClassCourseId = 1,
                            CourseId = 1,
                            SchoolClassId = 1
                        },
                        new
                        {
                            SchoolClassCourseId = 2,
                            CourseId = 2,
                            SchoolClassId = 2
                        });
                });

            modelBuilder.Entity("Labb2Linq.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<string>("StudentFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SchoolClassId = 1,
                            StudentFirstName = "Anders",
                            StudentLastName = "Pettersson"
                        },
                        new
                        {
                            StudentId = 2,
                            SchoolClassId = 1,
                            StudentFirstName = "Peter",
                            StudentLastName = "Karlsson"
                        },
                        new
                        {
                            StudentId = 3,
                            SchoolClassId = 1,
                            StudentFirstName = "Lisa",
                            StudentLastName = "Persson"
                        },
                        new
                        {
                            StudentId = 4,
                            SchoolClassId = 1,
                            StudentFirstName = "Stina",
                            StudentLastName = "Alexandersson"
                        },
                        new
                        {
                            StudentId = 5,
                            SchoolClassId = 1,
                            StudentFirstName = "Fredrik",
                            StudentLastName = "From"
                        },
                        new
                        {
                            StudentId = 6,
                            SchoolClassId = 2,
                            StudentFirstName = "Anna",
                            StudentLastName = "Persson"
                        },
                        new
                        {
                            StudentId = 7,
                            SchoolClassId = 2,
                            StudentFirstName = "Åke",
                            StudentLastName = "Stolt"
                        },
                        new
                        {
                            StudentId = 8,
                            SchoolClassId = 2,
                            StudentFirstName = "Vera",
                            StudentLastName = "Strömberg"
                        },
                        new
                        {
                            StudentId = 9,
                            SchoolClassId = 2,
                            StudentFirstName = "Kim",
                            StudentLastName = "Fredlund"
                        },
                        new
                        {
                            StudentId = 10,
                            SchoolClassId = 2,
                            StudentFirstName = "Robin",
                            StudentLastName = "Andersson"
                        });
                });

            modelBuilder.Entity("Labb2Linq.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            TeacherFirstName = "Maja",
                            TeacherLastName = "Lundström"
                        },
                        new
                        {
                            TeacherId = 2,
                            TeacherFirstName = "Anas",
                            TeacherLastName = "Qlok"
                        },
                        new
                        {
                            TeacherId = 3,
                            TeacherFirstName = "Reidar",
                            TeacherLastName = "Qlok"
                        });
                });

            modelBuilder.Entity("Labb2Linq.Models.Course", b =>
                {
                    b.HasOne("Labb2Linq.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb2Linq.Models.SchoolClassCourse", b =>
                {
                    b.HasOne("Labb2Linq.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb2Linq.Models.SchoolClass", "SchoolClass")
                        .WithMany()
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb2Linq.Models.Student", b =>
                {
                    b.HasOne("Labb2Linq.Models.SchoolClass", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
